[Paperboat]
title = Paperboat Portfolio
author = Name Nameson
description = "Art, Visuals and Code"
email = name@exsample.com

[Layout]
; Layout options are: default, topbar, sidebar
navigation = default
